- src/constraint.rs
- src/schema.rs
- src/system.rs
- src/types.rs
*Issue #15*
This PR works on implementation of  `TypeCache`.
*Change:*
- creates a struct `TypeCache` which helps with the cycling issue as described in #15.
- creates a type `TypeId` which represents the index/id for Types stores in `TypeCache`.
- modifies the `Constraint`s to store `Vec<TypeId>` instead of `Vec<Type>`.
- modifies `Scehma` struct to store the `TypeCache` that is created while loading the schema instead of a `HashMap<String, Type>`. (This `TypeCache` will help in resolving the `TypeId`s while validation)
- modifies get_types() in Schema as it needs to return an Iterator and not the `HashMap`/ `TypeCache` stored inside `Schema`.(I will work on this on next PR)
> adds implementation of TypeCache

- src/schema.rs
- src/system.rs
*Issue #18*
This PR works on implementation of `SchemaTypeIterator` which can be used by `Schema` to return associated `Type`s.
*Changes:*
- adds a new struct `SchemaTypeIterator` and its `Iterator` implementation.
- adds a new method in `TypeStore` to return all the `Type`s stored inside it.
- changed `get_types` signature to return `SchemaTypeIterator` instead of `HashMap`.
> adds SchemaTypeIterator implementation

- Cargo.toml
- src/constraint.rs
- src/isl.rs
- src/lib.rs
- src/schema.rs
- src/system.rs
- src/types.rs
This PR works on changes for implementation of a public facing API for constructing types/constraints programmatically.
*Changes:*
- Adds implementation of new public facing API `IslType`, `IslConstraint`, `IslTypeRef` (stored in `isl` module)
- Renames `Type` to `TypeDefinition`
- Renames current `TypeRef` to `IslTypeRef`
- Creates a `TypeRef` which has a `TypeId` and reference to `TypeStore`
- Bug fix for self referencing types using parent information stored in `TypeStore`
- `TypeDefinition` field name is changed to be an `Option` to store both anonymous and named types
- doc comment changes
*Fixes #23*
*Fixes #14*
> adds changes for constructing types/constraints programmatically

- src/constraint.rs
- src/isl.rs
- src/schema.rs
- src/system.rs
- src/types.rs
*Issues:*
Fixes #28
Fixes #20
Adds changes for  using `&mut PendingTypes` for `SharedPendingTypes `and `&mut TypeStore` for  `SharedTypeStore.` 
*Changes:*
- removes type alias SharedTypeStore and SharedPendingTypes
- changes all methods loading a schema to use &mut PendingTypes and &mut TypeStore instead.
- renames variables to use the name `pending_types` instead of `context`
> adds changes to type aliases SharedPendingTypes and SharedTypeStore

- src/authority.rs
- src/system.rs
*Issue:*
Fixes #17
This PR works on renaming `Authority` trait to a more proper name `DocumentAuthority` now that it doesn't perform the end-to-end role of an authority.
> rename `Authority` trait to `DocumentAuthority`

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/isl_type.rs
- src/isl/isl_type_reference.rs
- src/isl/mod.rs
- src/lib.rs
- src/schema.rs
- src/system.rs
- src/types.rs
*Issue:*
Fixes #25 
- adds `IslType` enum with two different implementations for anonymous and named ISL types
- adds `TypeDefinition` enum with two implementations for anonymous and named type definitions
- Fixes a bug in `PendingType`s to store correct `TypeId` in `Constraint`s (`type_id + type_store.types_by_id.len()`)
*Tests:*
adds changes for using corresponding anonymous/named types in unit tests.
> adds changes for anonymous and named `TypeDefinition`s and `Isl*` implementations

- src/authority.rs
- src/isl/isl_import.rs
- src/isl/isl_type.rs
- src/isl/mod.rs
- src/schema.rs
- src/system.rs
- src/types.rs
*Issue #34, #22*
This PR works on adding changes for `IslImport`
*Changes:*
- Implementation of IslImport to represent an import in ISL.
- Changes in `Resolver` `load_schema` and `schema_from_elements` method signature to not load imports to `type_store` when in the root of schema.
- New methods in type_store and pending_types to store imports separately.
- Changes in schema ` get_types` to rightly return only named types within that schema and not include the import types
- Changes in `SchemaTypeIterator` to return appropriate types within the schema and changes in `get_imports` to return import types.
*Tests:*
Ran all the unit tests as well as examples to verify if everything works fine.
*Questions:*
- Currently `get_types` returns named types + core types …
> adds changes for implmentation of `IslImport`

- Cargo.toml
- src/isl/isl_type.rs
- src/isl/mod.rs
- src/isl/util.rs
*Issue #10*
This PR works on creating ISL ranges.
*Changes:*
* adds changes for ISL `Range`
*  `RangeBoundaryValue`: represents a range boundary value (i.e. min, max or a value in terms of `RangeBoundaryValueType`)
* `RangeBoundaryValueType`: represents a range boundary value which can be a `Decimal`/`Integer`/...
* `RangBoundaryType`: defines exclusivity of the range boundary
* adds a bugfix for unordered types comparison (a new `PartialEq` implementation for `IslTypeImpl`)
* adds unit tests related to ranges
*Test:*
Adds unit tests for ISL `Range`s
> adds changes for implementation of ISL ranges

- src/isl/mod.rs
- src/isl/util.rs
This PR works on changes for implementation of `contains()` in `Range`.
*Changes:*
* adds `contains()` for Range struct
* Note: TODO - implement contains for Timestamp ranges.
*Tests:*
* adds unit tests for `contains()`
> Implements `contains()` for `Range`s

- src/isl/core_types.rs
- src/isl/isl_type_reference.rs
- src/isl/mod.rs
- src/schema.rs
- src/system.rs
- src/types.rs
- src/violation.rs
*Issue #13*
This PR works on implementing [ISL core types](https://amzn.github.io/ion-schema/docs/spec.html#core-types)
*Changes:*
* adds `CoreIslType` and `CoreISLTypeDefinition` for lob, number, text, any
core types implementation
* renames `TypeDefintionImpl` method
`parse_from_isl_type_and_update_pending_types`
* adds changes to `TypeStore`, `PedningTypes` to store core types
* adds unit tests for this change
* `core_types.rs` stores `Hashmap` of ISL core types and their definition
*Test:*
adds tests for ISL core types
> Adds changes for core isl types

- Cargo.toml
- src/isl/isl_constraint.rs
- src/isl/isl_import.rs
- src/isl/isl_type.rs
- src/isl/isl_type_reference.rs
- src/lib.rs
- src/system.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
This PR adds changes for integrating [ion-schema-tests](https://github.com/amzn/ion-schema-tests)
*Changes:*
* Bug fix: Found null instead of lists while converting
`Vec<OwnedElement>` to `Vec<IslTypeRef>`
* Removed an invalid check to require all 'type::' annotated types to be
named types
* Bug Fix: Found `null.*` as alias for type reference
* Made types module public to be used for tests
* Added `$null` in derived built-in types
* Added `schema_type_from_element()`
* Adds `type: any` as default type constraint if no type constraint
available
*Tests:*
* Adds validation tests from [ion-schema-tests](https://github.com/amzn/ion-schema-tests)
> Adds changes for integrating ion-schema-tests

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/schema.rs
- src/types.rs
*Issue #10*
This PR works on the implementation of `fields` constraint.
*Changes:*
- adds implementation of `IslConstraint::Fields`
- adds implementation of `FieldsConstraint`
```
fields: { <FIELD>... }
```
Declares one or more field constraints of a struct, where `<FIELD>` is defined as:
```
<SYMBOL>: <VARIABLY_OCCURRING_TYPE>
```
For more information: https://amzn.github.io/ion-schema/docs/spec.html#fields
*Tests:*
Adds unit tests as following:
- Owned element --> ISL type
- ISL type --> Type Definition
- Owned elements --> Schema
> adds changes for fields constraint implementation

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/schema.rs
- src/types.rs
- src/violation.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of contains constraint.
*Grammar:*
```ANTLR
<CONTAINS> ::= contains: [ <VALUE>... ]
```
https://amzn.github.io/ion-schema/docs/spec.html#contains
* adds implementation of `ContainsConstraint`
* adds `enum` variant `IslConstraint::Contains` and `Constraint::Contains`
* `contains()` method to create `IslConstraint::Contains` and
`Constraint::Contains` programmatically
* adds unit tests for contains constraint implementation (for
programmatically creating contains, loading schema using contains and
validation of contains)
* adds `ViolationCode` `MissingValue` for a missing value found during
contains validation
*Tests:*
added unit tests for `contains` implementation. …
> adds changes for `contains` constraint implementation

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- src/violation.rs
*Issue #9 #10*
This PR works on adding implementation of `container_length` constraint.
*Grammar:*
```ANTLR
<CONTAINER_LENGTH> ::= container_length: <INT>
| container_length: <RANGE<INT>>
```
https://amzn.github.io/ion-schema/docs/spec.html#container_length
* adds `IslConstraint::ContainerLength` and `Constraint::ContainerLength`
enum variants
* adds `IslLength` that can be used by `byte_length`, `codepoint_length` and
`container_length` constraints
* fixes bug for non negative integer/integer ranges in occurs constraint
* adds validation logic for `container_length` constraint in
`ContainerLengthConstraint` implementation
* adds `ViolationCode::InvalidLength` for any invalid length for constraints like …
> adds changes for `container_length` implementation

- src/authority.rs
- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/isl_import.rs
- src/isl/isl_type.rs
- src/isl/isl_type_reference.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/system.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue: #69*
This PR works on adding all the changes suggested by Clippy (Rust linter).
*Changes:*
The changes are incorporated in 3 separate commits:
- Phase 1: clippy automated fixes for ion-schema crate
- Phase 2: clippy automated changes for tests folder
- Phase 3: manually added clippy suggestions
* uses `ok_or_else` instead of `ok_or`
* removes unnecessary `collect()` usage
* remove `fn main()` from doctests
* removes unnecessary lifetime usage
* uses `assert!` instead of `assert_eq!` for `bool` comparison
* uses `if let` instead of `unwrap`
* `default()` implementations for TypeStore and PendingTypes
* (Overridden clippy suggestion) uses self named constructors for `Range`
- Bug Fix: while loading a schema tested as per a doc test in `isl` module
> adds changes for clippy fixes and suggestions

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
*Issue #9 #10*
This PR works on adding implementation of `byte_length` and `codepoint_length` constraint.
*Grammar:*
```ANTLR
<BYTE_LENGTH> ::= byte_length: <INT>
| byte_length: <RANGE<INT>>
<CODEPOINT_LENGTH> ::= codepoint_length: <INT>
| codepoint_length: <RANGE<INT>>
```
https://amzn.github.io/ion-schema/docs/spec.html#byte_length
https://amzn.github.io/ion-schema/docs/spec.html#codepoint_length
* adds `IslConstraint::CodePointLength` and`IslConstraint::ByteLength` enum variants
*  adds `Constraint::CodePointLength` and `Constraint::ByteLength`
enum variants
* adds validation logic for `byte_length` and `codepoint_length` constraint
* adds unit tests for `byte_length` and `codepoint_length` constraint
*Tests:* …
> adds changes for `byte_length` and `codepoint_length` constraint

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/schema.rs
- src/types.rs
- src/violation.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `element` constraint.
*Grammar:*
```ANTLR
<ELEMENT> ::= element: <TYPE_REFERENCE>
```
https://amzn.github.io/ion-schema/docs/spec.html#element
* adds `Elemnt` enum variants for `IslConstraint` and `Constraint`
* adds `ElementConstraint` implementations
* adds validation logic for element
* adds `ViolationCode::ElementMismatched` enum variant
* adds unit tests for element
*Tests:*
added unit tests for `element` implementation.
- adds tests for programmatically creating `element` constraint
- adds tests for loading a schema using `element` constraint 
- adds validation test for `element` constraint
> adds changes for `element` constraint implementation

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- src/violation.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `annotations` constraint.
*Grammar:*
```ANTLR
<ANNOTATION> ::= <SYMBOL>
| required::<SYMBOL>
| optional::<SYMBOL>
<ANNOTATIONS_MODIFIER> ::= required::
| ordered::
| closed::
<ANNOTATIONS> ::= annotations: <ANNOTATIONS_MODIFIER>... [ <ANNOTATION>... ]
```
https://amzn.github.io/ion-schema/docs/spec.html#annotations
* adds `Annotations` enum variants for `IslConstraint` and `Constraint`
* adds `Annotation` and `AnnotationModifier` implementations to be used to
represent annotations
* adds `AnnotationsConstraint` implementation
* adds validation logic for annotations
* adds `ViolationCode::AnnotationMismatched`,
`ViolationCode::UnexpectedAnnotation`, …
> adds changes for `annotations` constraint implementation

- Cargo.toml
- examples/schema.rs
- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `precision` constraint.
*Grammar:*
```ANTLR
<PRECISION> ::= precision: <INT>
| precision: <RANGE<INT>>
```
https://amzn.github.io/ion-schema/docs/spec.html#precision
* adds changes to upgrade to v0.10.0 for `ion-rs`.
* adds `Precision` enum variants for `IslConstraint` and `Constraint`
* adds `PrecisionConstraint` implementations
* adds changes for validating precision range (_Note: precision range must be equal to or greater than 1_)
* adds validation logic for precision
*Tests:*
added unit tests for `precision` implementation.
- adds tests for programmatically creating `precision` constraint
- adds tests for loading a schema using `precision` constraint 
- …
> adds implementation of `precision` constraint

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `scale` constraint.
*Grammar:*
```ANTLR
<SCALE> ::= scale: <INT>
| scale: <RANGE<INT>>
```
https://amzn.github.io/ion-schema/docs/spec.html#scale
* adds changes in range construction to check for annotation `range`.
* adds `Scale` enum variants for `IslConstraint` and `Constraint`
* adds `ScaleConstraint` implementations
* adds validation logic for `scale` constraint
*Tests:*
added unit tests for `scale` implementation.
- adds tests for programmatically creating `scale` constraint
- adds tests for loading a schema using `scale` constraint 
- adds validation tests for `scale` constraint
> adds implementation of `scale` constraint

- Cargo.toml
- examples/schema.rs
This change eliminates transitive dependencies on `ion-c`,
`ion-c-sys`, `cmake`, and `clang`.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Updated dependency on ion-rs to v0.11.0

- Cargo.toml
Bumps the crate version to v0.3.0 in anticipation of another dev release. This PR depends on #85.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Version bump to v0.3.0

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `timestamp_precision` constraint.
*Grammar:*
```ANTLR
<TIMESTAMP_PRECISION_VALUE> ::= year
| month
| day
| minute
| second
| millisecond
| microsecond
| nanosecond
<TIMESTAMP_PRECISION> ::= timestamp_precision: <TIMESTAMP_PRECISION_VALUE>
| timestamp_precision: <RANGE<TIMESTAMP_PRECISION_VALUE>>
```
https://amzn.github.io/ion-schema/docs/spec.html#timestamp_precision
* adds `TimestampPrecison` range implementation
* adds `TimestampPrecison` enum variants for `IslConstraint` and `Constraint`
* adds `TimestampPrecisonConstraint` implementations
* adds changes for validating timestamp precision range (_Note: timestamp precision range must be equal to or greater …
> adds implementation of `timestamp_precision` constraint

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
This PR adds the reverted change for timestamp_precision constraint implementation and adds fractional seconds related changes.
*Changes:*
The second commit is the fractional seconds related change (https://github.com/amzn/ion-schema-rust/pull/90/commits/37797f2219bb13a267e0d4e18d2fd1f23462e521)
First commit is just the same as reverted commit  (#87)
*Test:*
Ran all unit tests for this change.
> adds `timetstamp_precision` constraint implementation with fractional seconds related change

- src/authority.rs
- src/result.rs
- src/system.rs
*Issue #80*
This PR adds more documentation around usage of `system` and `authority` modules.
- adds example for `SchemaSystem` usage.
- adds example for `DocumentAuthority` usage.
- makes `TypeStore` and `PendingTypes` method `pub(crate)`.  These structs are only used for internal implementation.
- adds document comments for `result` module.
- changed incorrect document type links to struct/trait definitions.
> adds usage examples for documentation of `system` and `authority`

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
- src/types.rs
- src/violation.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `valid_values` constraint.
*Grammar:*
```ANTLR
<VALID_VALUES> ::= valid_values: [ <VALUE>... ]
| valid_values: <RANGE<NUMBER>>
| valid_values: <RANGE<TIMESTAMP>>
```
https://amzn.github.io/ion-schema/docs/spec.html#valid_values
* adds changes for `Number` range implementation (https://github.com/amzn/ion-schema-rust/pull/92/commits/d184e29462a756524e68c98d1a46767a7a1ace63)
(_Note: `Timestamp` ranges are not completely implemented yet, refer #91_) 
* adds `ValidValues` enum variants for `IslConstraint` and `Constraint`
* adds `ValidValuesConstraint` implementations
* adds validation logic for `valid_values` 
*Tests:*
added unit tests for `valid_values` …
> adds implementation of `valid_values` constraint

- Cargo.toml
- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/schema.rs
- src/types.rs
- src/violation.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `regex` constraint.
*Grammar:*
```ANTLR
<REGEX> ::= regex: <STRING>
| regex: i::<STRING>
| regex: m::<STRING>
| regex: i::m::<STRING>
```
https://amzn.github.io/ion-schema/docs/spec.html#regex
* adds `regex` crate dependency
* adds `Regex` enum variants for `IslConstraint` and `Constraint`
* adds `RegexConstraint` implementations 
(_Note: Not all features of regex are supported as per Ion schema specification hence there is a preprocessing done on the regex to allow only the supported features_)
* reference for preprocessing regex is as per `ion-schema-kotlin` implementation.
* adds validation logic for `regex`
* adds `ViolationCode` for `RegexMismatched` …
> adds changes for `regex` constraint implementation

- Cargo.toml
This PR works on version bump to `v0.4.0`.
> Version bump to v0.4.0

- src/isl/isl_type_reference.rs
- src/isl/mod.rs
- src/schema.rs
- src/system.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue #12*
This PR works on implementation of type references that are annotated with `nullable`.
- Adds a check for `nullable` annotation on type references (only allows for built in type references e.g. `{ type: int }`)
*Test:*
Adds unit tests for nullable type references and removes skip list tests.
> adds changes for 'nullable' annotated type references

- src/constraint.rs
- src/isl/isl_type_reference.rs
- src/lib.rs
- src/system.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue #103*
This PR adds implementation of `document` type.
https://amzn.github.io/ion-schema/docs/spec.html#type-system
> document: represents a series of top-level values
* adds `IonSchemaElement` implementation
* `TypeRef` validate method now uses `IonSchemaElement` as input
* `TypeDefinitionImpl`'s `parse_from_isl_type` method now returns a `TypeId`
instead of `TypeDefinitionImpl`
* adds `nullable` annotation check for non built in type references to
return an error
* Remove `document` type tests from skip list
* adds `id()` for `TypeRef` to get the `TypeId` of that `TypeRef`
* adds doc examples
*Tests:*
adds unit tests for document type (removes previously unsupported tests from skip list)
> adds implementation for `document` type

- .gitmodules
- wasm-schema-sandbox/.gitignore
- wasm-schema-sandbox/Cargo.toml
- wasm-schema-sandbox/LICENSE_APACHE
- wasm-schema-sandbox/LICENSE_MIT
- wasm-schema-sandbox/README.md
- wasm-schema-sandbox/src/lib.rs
- wasm-schema-sandbox/tests/web.rs
- wasm-schema-sandbox/www/.gitignore
- wasm-schema-sandbox/www/LICENSE-APACHE
- wasm-schema-sandbox/www/LICENSE-MIT
- wasm-schema-sandbox/www/bootstrap.js
- wasm-schema-sandbox/www/css/ion-schema-sandbox.css
- wasm-schema-sandbox/www/index.html
- wasm-schema-sandbox/www/index.js
- wasm-schema-sandbox/www/package.json
- wasm-schema-sandbox/www/webpack.config.js
This PR works on adding Ion schema sandbox using Web Assembly.
* adds Cargo.toml and README.md for the wasm-schema-sandbox
* adds ion-schema-rust va;lidation logic to be generated as wasm
* adds index.html and index.js containing the web app contents for sandbox
* adds ace-builds as submodule which provides Ion editors for sandbox
*Test:*
adds a wasm-bindgen test
> adds `wasm-schema-sandbox` to `ion-schema-rust` repository

- README.md
This PR works on changes for `README` example.
- correct output to match with updated example in `README`
- adds changes for import statements in example
- uses `Display` for `OwnedElement` in example now that its available
*Test:*
Tested by running the example program locally.
> adds changes for `README` example

- Cargo.toml
- README.md
This PR bumps version to v0.5.0 and adds reference links to README.
* adds version bump change in `Cargo.toml`
* adds reference link to Ion schema sandbox web tool
* adds reference link to Ion schema GitHub website's cookbook examples
> bumps version to v0.5.0 and adds reference links to README

- wasm-schema-sandbox/Cargo.toml
This PR removes dependency to `wee_alloc` and `console_error_panic_hook`.
> Removes dependency to `wee_alloc` and `console_error_panic_hook`

- src/system.rs
*Issue #113*
This PR works on adding a check for ISL version marker.
*Test:*
Adds tests to verify invalid or unsupported version markers return an error.
_Note: This PR is created using PR #116 as base_
> adds changes to check for ISL version marker in schema content

- src/schema.rs
- src/system.rs
- src/types.rs
This PR works on adding changes for allowing validation for built-in types.
*Example of the issue:*
```rust
let schema = load_schema_from_text(r#" // No schema defined, uses built-in types"#);
// The following was only checking for types defined within schema but not built-in types
let type_to_validate = schema.get_type("int"); 
type_to_validate.validate(load_value("5"));
```
* adds implementation for validation of `BuilInTypeDefinition`
* removes redundant `TypeDefinition` checks for validation
* adds method in `TypeStore` to retrieve either a built-int type id or a defined type id based on the given type name
*Test:*
* adds test for built-in type validation
> adds changes to allow validating built-in types for TypeRef validation

- src/isl/isl_type_reference.rs
- src/system.rs
- src/types.rs
*Issue #114*
This PR works on resolving issue when loading a type definition that uses a type reference from following part of schema.
*Example of the issue:*
```
type:: {
name: a,
type: b // <--- this is defined in the following part of schema
},
type::{
name: b,
type: int
}
```
The above schema throws following error:
```
UnresolvableSchemaError { description: "Could not resolve type reference: \"b\" does not exist" }
```
*Solution:*
As per above example whenever we discover an unknown type reference like `b` (which might be defined in following part of schema), 
1. add that type definition using the `TypdefinitionImpl#new_deferred_type_def()` to the `PendingTypes`. 
2. when updating `TypeStore` with the `PendingTypes`, verify if that deferred type definition …
> Fixes loading type definition that uses type references from the following part of schema

- src/system.rs
**Issue #, if available:**
None
**Description of changes:**
When I was testing something out with `ion-schema-rust`, I saw that the error message said "Unsupported Ion Schema version: ${it.stringValue()}"—this changes it to use `format!` instead of Kotlin string interpolation so that the message will be like  "Unsupported Ion Schema version: $ion_schema_0_1"
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
> Fix error message for unsupported ISL version

- src/constraint.rs
- src/isl/isl_range.rs
- src/isl/mod.rs
- src/isl/util.rs
*Issue #112*
This PR works on adding `Display` implementation of `Range`.
*Test:*
adds unit tests for `Display` implementation of `Range`.
*Base PR:*
https://github.com/amzn/ion-schema-rust/pull/120
*TODO for follow up PR*
- There are many places in the error messages where we could now use the `Element` `Display` implementation of ion-rs.
> adds `Display` implementation of `Range`

- wasm-schema-sandbox/README.md
- wasm-schema-sandbox/src/lib.rs
This PR updates `wasm-schema-sandbox` with latest `ion-rust` Element API changes. 
- changes all `OwnedElement` references to `Element` as `ion-rust` latest version renamed the struct
- changes README.md with `ion-schema-rust` clone instruction.
*Test:*
Locally tested with `wasm-pack build`.
> Updates `wasm-schema-sandbox` package with latest `ion-rust` Element API changes

- src/isl/isl_type.rs
- src/isl/mod.rs
- src/system.rs
This PR adds an error check for a top level type definition `name` field.
- modifies `IslSchema#types()` to return `IslType` instead of `IslTypeImpl`
- adds `name()` method for `IslType`
- adds an error check for top level type def `name` field
- adds a unit test for this error check
*Test:*
Adds a unit test for the error check
> Adds an error check for top level type definition's `name` field

- src/isl/isl_type.rs
- src/system.rs
- src/types.rs
This PR works on issues related to `name` field in a type definition as mentioned in https://github.com/amzn/ion-schema-rust/pull/124#discussion_r1023352762.
*Issue:*
Type definitions described as below with multiple `name` fields and of non symbol type should return an error:
```
// invalid type definition with multiple names
type:: {
name: my_type,
name: new_type
}
// invalid type definition which has `name` field with non symbol type
type:: {
name: "my_type"
}
```
- adds check for multiple `name` fields in a type definition
- adds check for non symbol `name` field values
- modifies doc tests to not accept string as type name
*Tests*
- adds unit tests for both occurrence and type of `name` field in type definition
> adds check for `name` field's Ion type and occurence in type definition

- Cargo.toml
This PR bumps version to `v0.6.0`.
> bumps version to `v0.6.0`

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/isl_range.rs
- src/isl/mod.rs
- src/schema.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `utf8_byte_length` constraint.
*Grammar:*
```ANTLR
utf8_byte_length: <INT>
utf8_byte_length: <RANGE<INT>>
```
https://amzn.github.io/ion-schema/docs/isl-1-0/spec#utf8_byte_length
* adds changes for `utf8_byte_length` constraint implementation
* adds `Utf8ByteLength` enum variants for `IslConstraint` and `Constraint`
* adds `Utf8ByteLengthConstraint` implementations
* adds validation logic for `utf8
_byte_length`
* adds unit tests for `utf8_byte_length`
*Tests:*
added unit tests for `utf8_byte_length` implementation.
- adds tests for programmatically creating `utf8_byte_length` constraint
- adds tests for loading a schema using `utf8_byte_length` constraint 
- …
> adds changes for `utf8_byte_length` constraint

- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/schema.rs
- ion-schema/src/types.rs
- ion-schema/tests/ion_schema_tests_runner.rs
*Issue #9 #10*
This PR works on adding implementation of `timestamp_offset` constraint.
*Grammar:*
```ANTLR
timestamp_offset: [ "[+|-]hh:mm"... ]
```
https://amzn.github.io/ion-schema/docs/isl-1-0/spec#timestamp_offset
* adds changes for `timestamp_offset` constraint implementation
* adds a util implementation of `TimestampOffset` to create `timestamp_offset` constraint with valid  timetsamp offset values
* adds `TimestampOffsetLength` enum variants for `IslConstraint` and `Constraint`
* adds `TimestampOffsetConstraint` implementations
* adds validation logic for `timestamp_offset`
* adds unit tests for `timestamp_offset`
*Tests:*
added unit tests for `timestamp_offset` implementation.
- adds tests for …
> adds changes for `timestamp_offset` constraint

- ion-schema/src/lib.rs
- ion-schema/src/result.rs
- ion-schema/src/violation.rs
This PR works on making `violation` module public and adding `PartialEq` for `Violation` and `IonSchemaError`
* adds `PartialEq` implementation for `IonSchemaError`
* Derives `PartialEq` for `ViolationCode` and Violation
* makes violation module public
----
> adds `PartialEq` for `Violation` and `IonSchemaError` and makes `violation` module public

- ion-schema-tests-runner/src/generator.rs
- ion-schema-tests-runner/src/model.rs
- ion-schema/src/authority.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/lib.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
- ion-schema/src/violation.rs
- wasm-schema-sandbox/src/lib.rs
This PR works on adding ISL struct in the violation messages for anonymous type definitions. This adds more context in the violation message regarding where in the type definition the violation occurred.
* adds `Display` for `TypeDefinition`
* adds `isl_type_struct` field in `IslTypeImpl` and `TypeDefinitionImpl` that represents ISL type struct in string format
* remove usage of `Debug` for violation messages and instead uses `Display`. (Change all the `{:?}` usage to `{}`)
* modifies tests accordingly
*Example of a violation message:*
Schema:
```
type::{
name: one_of_type,
one_of: [ { type: string, codepoint_length: range::[1, 10] }, decimal ],
}
```
Type to be validated: 
```
one_of_type
```
Ion value used for validation: 
```
1
```
New violation message changed with this PR:
``` …
```
> Modifies violation messages to include ISL struct for annoymous type definitions

- ion-schema-tests-runner/tests/ion-schema-tests-1-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
This PR works on adding changes for allowing open content within schema and adds APIs to retrieve open content.
* adds `open_content()` in `IslType` as well `IslSchema` to retrieve open content
* adds `load_isl_schema()` that load a schema content as an internal ISL model which can be programmatically manipulated
* adds related tests for open content
_Note_: `IslSchema#open_content()` only provides top level open content. For open content in type definition  added `IslType#open_content()`
*Test:*
- adds unit tests inside `system` and `isl` modules
- allows test files from `ion-schema-tests` to verify open content is allowed
----
> adds changes to allow open content within schema and adds APIs to retrieve open content

- ion-schema/src/constraint.rs
- ion-schema/src/ion_path.rs
- ion-schema/src/lib.rs
- ion-schema/src/types.rs
- ion-schema/src/violation.rs
- wasm-schema-sandbox/src/lib.rs
This PR works on adding changes to add path information for an Ion value that was invalid and resulted into violation.
* adds implementation of `IonPath` along with `IonPathElement`
* adds `Debug` implementation for `IonPath` as that will be sued for schema sandbox
* `Into<Element>` implementation helps serialize `IonPath` as an SExpression
```
type::{
name: customer,
type: struct,
fields: {
addresses: {
type: list,
element: {
type: struct,
fields: {
city: { type: string, codepoint_length: range::[8, max] },
state: symbol
}
}
}
}
}
```
```
{
addresses: [
{ city: "Seattle", state: WA },
{ city: "Portland", state: OR },
{ city: "San Francisco", state: CA }
]
}
```
```
Violation {
constraint: "{type: string, codepoint_length: range::[8, max]}",
code: TypeConstraintsUnsatisfied,
message: …
```
> adds `IonPath` implementation for `Violation`

- ion-schema-tests-runner/src/generator.rs
- ion-schema-tests-runner/tests/ion-schema-tests-1-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/lib.rs
- ion-schema/src/schema.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
- ion-schema/tests/reexport_external.rs
This PR works on adding version configuration changes to allow ISL 2.0 support.
- fixes an issue with range construction which had a missing type check for range construction (95e97c973dfa06083227bfabda4813cceddaaefe)
- adds schema versioning configuration for all internal methods that were used to load schema or ISL model using an enum `IonSchemaLanguageVersion`(529fa2d02425d65bbda3062cda87ae0b5756c89e)
- `isl_type`, `isl_type_reference` and `isl_constraint` contains two modules with specific implementation of types/type references and constraints based on ISL version(`v_1_0` and `v_2_0`). This will help with easier API modifications with new major/minor version release.
- All the previously defined schema model structs/enums are now hidden inside wrapper classes which helps with hiding …
> adds initial implementation to support ISL 2.0

- ion-schema-tests-runner/Cargo.toml
- ion-schema-tests-runner/src/generator.rs
- ion-schema-tests-runner/src/model.rs
- ion-schema/Cargo.toml
- ion-schema/src/authority.rs
- ion-schema/src/constraint.rs
- ion-schema/src/ion_path.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_import.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/lib.rs
- ion-schema/src/nfa.rs
- ion-schema/src/schema.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
- wasm-schema-sandbox/src/lib.rs
This PR works on updating dependency of `ion-rs` to v0.16.0 and adds related changes.
* Uses full names for `as_*` methods:
* `as_str` -> `as_string`
* `as_int` -> `as_integer`
* `as_sym` -> `as_symbol`
* `as_f64` -> `as_float`
*  `element_reader().read_one()` -> `Element::read_one()`
* `element_reader().read_all()` ->`Element::read_all()` 
* Uses `Symbol::from(TEXT)` instead of `text_token(TEXT)`
* For List and Sexp (Sequences) change `iter()` -> `elements()`
* Uses new Element builders e.g. `list_builder()` , `sexp_builder()`
----
> Update `ion-rs` to `v0.16.0`

- ion-schema-tests-runner/src/model.rs
- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/schema.rs
- ion-schema/src/types.rs
This PR works on adding implementation of `exponent` constraint.
```ANTLR
<EXPONENT> ::= exponent: <INT>
| exponent: <RANGE_INT>
```
https://amazon-ion.github.io/ion-schema/docs/isl-2-0/spec#exponent
* adds changes for `exponent` constraint implementation
* adds `Exponent` enum variants for `IslConstraintImpl` and `Constraint`
* adds `ExponentConstraint` implementations
* adds validation logic for `exponent`
* adds changes for `Range` to expect only List types while parsing from ISL.
* adds changes for Integer ranges to return error for empty ranges for which there aren't any valid values. 
(e.g. `range::[exclusive::2, exclusive::3]`)
added unit tests for `exponent` implementation.
- adds tests for programmatically creating `exponent` constraint
- adds tests for loading a schema using …
> adds implementation of `exponent` constraint for ISL 2.0

- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_import.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/schema.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
- ion-schema/src/violation.rs
This PR works on adding implementation of `element` constraint with `distinct` annotation for ISL 2.0.
```ANTLR
<ELEMENT> ::= element: <TYPE_REFERENCE>
| element: distinct::<TYPE_REFERENCE>
```
https://amazon-ion.github.io/ion-schema/docs/isl-2-0/spec#element
* adds changes for `element` constraint implementation
* adds check for `distinct` annotation when constructing `ElementConstraint`
* `ElementConstraint` now stores `require_distinct_elements` property which is a boolean and used for validation of distinct elements
* adds validation logic for distinct elements
* add check for null value for range `contains` method
* adds check to verify there is no occurs field on `element`
constraints' type reference
* adds new `ViolationCode` for `ElementNotDistinct`
* adds check for verifying …
> adds implementation of `element` constraint for ISL 2.0

- README.md
- ion-schema-tests-runner/Cargo.toml
- ion-schema-tests-runner/src/generator.rs
- ion-schema-tests-runner/src/model.rs
- ion-schema/Cargo.toml
- ion-schema/src/authority.rs
- ion-schema/src/constraint.rs
- ion-schema/src/ion_path.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/lib.rs
- ion-schema/src/nfa.rs
- ion-schema/src/schema.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
- wasm-schema-sandbox/src/lib.rs
This PR works on making `SchemaSystem` [Send and Sync](https://doc.rust-lang.org/nomicon/send-and-sync.html).
* Adds changes for making `SchemaSystem` use `Arc` instead of `Rc`.
* Use `Arc` instead of `Rc` for `Schema` and `TypeStore`.
* Adds changes for inserting schema to `resolved_schema_cache` once its loaded.
----
> adds changes for making `SchemaSystem` Send and Sync

- ion-schema-tests-runner/Cargo.toml
- ion-schema/Cargo.toml
This PR bumps `ion-schema` version to 0.7.0 and `ion-schema-tests-runner` version to v0.2.0.
----
> bumps version to 0.7.0

- ion-schema/src/violation.rs
- wasm-schema-sandbox/Cargo.toml
- wasm-schema-sandbox/src/lib.rs
This PR works on adding `flattened_violations()` that gets the leaf/core violations. This will be useful for `wasm-schema-sandbox` to include only the core violations.
- adds `flattened_violations()` to `Violation`.
-  adds accessor methods `ion_path`, `code`, `message` for `Violation`.
- adds changes for wasm methods to use `flattened_violations()` to render violations in sandbox.
https://desaikd.github.io/ion-schema/sandbox 
Create PR for the rendered view in `ion-schema` repository
----
> modifies `wasm-schema-sandbox` to use flattened violations

- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/Cargo.toml
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/schema.rs
- ion-schema/src/types.rs
- ion-schema/src/violation.rs
This PR works on adding struct fields related constraint field_names and closed:: modifier for fields constraint.
-  adds changes for `ieee754_float` constraint implementation
-  adds `Ieee754Float` enum variants for `IslConstraintImpl` and `Constraint`
-  adds Ieee754FloatConstraint implementations
-  adds validation logic for `ieee754_float`
- adds dependency to [`half`](https://crates.io/crates/half/) crate for binary16 conversion 
-  adds unit tests for `ieee754_float`
----
> adds implementation of `ieee754_float` constraint

- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/schema.rs
- ion-schema/src/types.rs
This PR adds implementation of annotations constraint ISL 2.0.
```
<ANNOTATIONS> ::= annotations: <ANNOTATIONS_MODIFIER>... [ <SYMBOL>... ]
| annotations: <TYPE_ARGUMENT>
<ANNOTATIONS_MODIFIER> ::= required::
| closed::
```
https://amazon-ion.github.io/ion-schema/docs/isl-2-0/spec#annotations
* adds support for standard and simple syntax for annotations constraint as per ISL 2.0
* adds enum `IslAnnotationsConstraint` which holds two variants for
standard and simple syntax of annotations constraint
* adds `Anotations2_0Constraint` to handle ISL 2.0 related annotations
validation based on a type reference
* adds unit tests for `annotations` constraint ISL 2.0
----
> adds implementation of annotations constraint ISL 2.0

- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/schema.rs
- ion-schema/src/types.rs
This PR works on adding implementation of `regex` constraint as per ISL 2.0.
* adds changes to support character classes in regex ISL 2.0 
* adds changes to return error when regex has annotations other than "i" and "m". 
* adds changes to return error for empty regex 
added unit tests for `regex` implementation.
----
> adds implementation of regex constraint ISL 2.0

- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/types.rs
This PR adds changes for timestamp ranges as per ISL 2.0.
* adds changes to allow unknown offsets on timestamp ranges for ISL 2.0
* adds changes to pass isl_version for `ValidValues` constraint
* adds changes to check for `exclusive` annotation on min/max range boundary value
* adds unit tests
----
> adds changes for timestamp ranges ISL 2.0

- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
This PR works on adding a variably occurring type reference implementation which will be used by the schema model.
```ANTLR
<VARIABLY_OCCURRING_TYPE_ARGUMENT> ::= { <OCCURS>, <CONSTRAINT>... }
| <TYPE_ARGUMENT>
<OCCURS> ::= occurs: <INT>
| occurs: <RANGE_INT>
| occurs: optional
| occurs: required
```
https://amazon-ion.github.io/ion-schema/docs/isl-2-0/spec#variably-occurring-type-arguments
* adds implementation of `IslVariablyOccurringTypeRef` in isl module.
* adds changes for converting `IslVariablyOccurringTypeRef` to `VariablyOccurringTypeRef` which contains resolved `TypeId`.
* Construction of `ordered_elements` and `fields` constraints takes in `IslVariablyOccurringTypeRef` instead of previous `IslTypeRef`.
* modifies unit tests for variably occurring type references.
----
_**By …
> adds implementation of `IslVariablyOccurringTypeRef`

- .github/workflows/rust.yml
- ion-schema-tests-runner/src/generator.rs
- ion-schema-tests-runner/tests/ion-schema-tests-1-0.rs
- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/lib.rs
- ion-schema/src/schema.rs
- ion-schema/src/system.rs
This PR works on adding fixes for ISL 2.0 open content.
* adds version information in the `IslSchema` model
* modifies generator for invalid schema tests to return `Ok` on violation
* modifies user reserved fields to not include reserved keywords and ISL 2.0 keywords
* modifies `isl_schema_from_elements` to consider the position of version marker for ISL 2.0
adds tests from `ion-schema-tests` for ISL 2.0 open content
----
> adds fixes for ISL 2.0 open content

- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/lib.rs
- ion-schema/src/system.rs
This PR works on adding `new_schema` for `SchemaSystem` and adds minor ISL model related fixes.
* adds new_schema and new_isl_schema in `SchemaSystem`
* adds fixes for user reserved fields
* `user_reserved_fields` should not consider validation for `imports`.
* Incorrect error "User reserved field must be non-null and unannotated struct" was thrown when `user_reserved_fields` didn't even exist. 
* adds version information for Annotation
* this will be useful to determine whether annotation is allowed or not
for each annotation in the annotations list
* adds a fix for inline import
* inline import should not accept `as` for ISL 2.0
* inline import should consider `as` open content for ISL 1.0
adds tests for `new_schema()` and `new_isl_schema()` .
----
_**By submitting this pull request, I …
> adds `new_schema()` for `SchemaSystem` and minor ISL model fixes

- ion-schema/Cargo.toml
This PR updates the `ion-schema` version to 0.8.0.
----
> Bumps the version to v0.8.0

- ion-schema-tests-runner/Cargo.toml
- ion-schema/Cargo.toml
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
This PR updates `ion-rs` dependency to v0.18.1.
- changes the imports statements for some of the modules.
- Uses `IonData` which provides `ion_eq` or Ion data model equivalence based on [Ion specification](https://amazon-ion.github.io/ion-docs/docs/spec.html).
----
> Updates `ion-rs` dependency to v0.18.1

- ion-schema/Cargo.toml
This PR removes the unused `chrono` dependency. `chrono` was added as part of timestamp ranges implementation but with the latest changes the dependency is no longer being used. 
----
> Removes unused `chrono` dependency

- ion-schema-tests-runner/src/lib.rs
- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/ranges.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/system.rs
- ion-schema/src/types.rs
This PR adds from remaining ion-schema-tests for ISL 2.0 and related bug fixes.
----
> adds ion-schema-tests and related fixes for ISL 2.0

- ion-schema/src/violation.rs
https://github.com/amazon-ion/ion-schema-rust/issues/209
small tweak for `ViolationCode` to simplify new violation codes when they are added if/when new versions of ISL add new constraints.
----
> fix(ion-schema): add non_exhaustive to ViolationCode enum

- ion-schema/Cargo.toml
This PR bumps version to v0.13.0 which includes changes to programmatically construct closed fields constraint.(#217) 
----
> Bumps version to v0.13.0

- ion-schema-tests-runner/Cargo.toml
- ion-schema-tests-runner/src/generator.rs
- ion-schema-tests-runner/tests/ion-schema-tests-2-0.rs
- ion-schema/Cargo.toml
- ion-schema/src/constraint.rs
- ion-schema/src/ion_schema_element.rs
- ion-schema/src/lib.rs
- ion-schema/src/nfa.rs
- ion-schema/src/system.rs
- ion-schema/src/type_reference.rs
- ion-schema/src/types.rs
- wasm-schema-sandbox/Cargo.toml
- wasm-schema-sandbox/src/lib.rs
Fixes #214 
Fixes #137
Changes `IonSchemaElement` so that it holds references to `Element`s rather than owning `Element`s. Details in PR tour 🗺️  comments.
----
> Makes IonSchemaElement use borrowed Elements
