amazon-ion/ion-schema-rust

- src/constraint.rs
- src/isl/isl_type_reference.rs
- src/result.rs
- src/schema.rs
- src/system.rs
- src/types.rs
- src/violation.rs
*Issues: #11, #9*
This PR works on changes for validation of logic constraints
*Changes:*
* adds Violations implementation to be used for specifying errors while
validation
* adds changes for storing core_types separately into type_store(this
simplifies the validation for core types)
* filled validate method for all logic constraints and `TypeDefinition`
*Test:*
adds unit tests based on validation of logic constraints
> adds changes for validation of logic constraints

- Cargo.toml
This PR adds changes for cargo file.
> adds changes for cargo file

- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/schema.rs
- src/types.rs
*Issue:* #10
This PR works on adding `ordered_elements` constraint.
*Changes:*
* adds `Occurs`constraint
* adds `OrderedElements` as constraint
*Test:*
* adds unit tests for `ordered_elements` constraint
> adds changes for ordered_elements constraint

- .github/workflows/rust.yml
- README.md
This PR updates README with latest repository changes.
*Changes:*
- renames workflow to CI Build
- adds crate and docs badges to README
> Updates README 

- src/constraint.rs
- src/isl/core_types.rs
- src/isl/isl_constraint.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/schema.rs
*Issue #10*
This PR works on validation of `ordered_elements`.
*Changes:*
* fills validate method for ordered_elements
* adds changes for occurs constraint validation
* adds tests for validation of ordered_elements
*Test:*
adds unit tests for validation of `ordered_elements`
> adds changes for `ordered_elements` validation

- .github/workflows/rust.yml
- tests/ion_schema_tests_runner.rs
*Issue #69*
This PR works on adding Clippy to GitHub Actions.
*Reference PR:*
https://github.com/amzn/ion-rust/pull/352
> adds clippy to GitHub Actions

- README.md
- src/lib.rs
- tests/reexport_external.rs
*Issue #77*
This PR works on reexporting dependency to `ion_rs`.
*Test:*
adds a unit test for reexporting external dependency.
_NOTE: A minor change for `README` is also added here._
> adds changes for reexporting ion_rs dependency

- README.md
*Issue #80*
This PR adds an example to load schema and validate in README.
> adds an example to load schema and validate in README

- src/schema.rs
- src/system.rs
- src/types.rs
*Issue #93*
This PR fixes an issue with self referencing type id calculation.
> Fixes the issue with calculating self referencing type ids

- README.md
- src/authority.rs
- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/isl_import.rs
- src/isl/isl_range.rs
- src/isl/isl_type.rs
- src/isl/isl_type_reference.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/result.rs
- src/schema.rs
- src/system.rs
- src/types.rs
*Issue #80*
This PR works on doc comment changes and adds more examples.
* adds doc examples
* adds doc comment examples
* adds module level documentation
* modifiies broken doc refrence link
* more doc comment modification
> adds doc comment changes

- Cargo.toml
- examples/schema.rs
- src/authority.rs
- src/constraint.rs
- src/isl/isl_constraint.rs
- src/isl/isl_import.rs
- src/isl/isl_range.rs
- src/isl/isl_type.rs
- src/isl/isl_type_reference.rs
- src/isl/mod.rs
- src/isl/util.rs
- src/lib.rs
- src/schema.rs
- src/system.rs
- src/types.rs
- tests/ion_schema_tests_runner.rs
This PR works on updating ion-rs to v0.14.0 and adds related changes.
- Mostly includes name changes in ion-rs
- Element -> IonElement
- OwnedElement -> Element
- SymbolToken -> IonSymbolToken
- Struct -> IonStruct
- Sequence -> IonSequence
- OwnedStruct -> Struct
- OwnedSequence -> Sequence
> Updates ion-rs to v0.14.0

- ion-schema/tests/ion_schema_tests_runner.rs
*issue:https://github.com/amzn/ion-schema-rust/issues/128*
This PR works on completing the test runner suite with test cases for all ISL constraints.
*Test:*
adds tests for test runner
> adds changes to complete `ion_schema_tests_runner`

- ion-schema/Cargo.toml
- ion-schema/src/constraint.rs
None
Updates ion-schema-rust, and does the bare minimum required for the crate to compile. There may be other improvements possible, but I did not seek them out.
----
> Update ion-rs to 0.15.0

- .github/workflows/rust.yml
This PR works on fixing clippy-check permissions for workflow.
----
> Fix permissions for clippy-check

- .github/workflows/rust.yml
- .gitmodules
- README.md
- ion-schema/Cargo.toml
- ion-schema/src/authority.rs
- ion-schema/src/constraint.rs
- ion-schema/src/isl/isl_constraint.rs
- ion-schema/src/isl/isl_import.rs
- ion-schema/src/isl/isl_range.rs
- ion-schema/src/isl/isl_type.rs
- ion-schema/src/isl/isl_type_reference.rs
- ion-schema/src/isl/mod.rs
- ion-schema/src/isl/util.rs
- ion-schema/src/system.rs
- wasm-schema-sandbox/README.md
This PR works changing the broken links for document comments in the repository.
- adds changes to change links for amazon-ion org
- adds changes for ISL spec doc links
----
> Fixes broken document links 

- ion-schema/Cargo.toml
This PR changes README path for `ion-schema` crate.
----
> Change README path for `ion-schema` crate

- .github/workflows/rust.yml
This PR updates CI workflow to use latest table rust toolchain.
----
> Updates CI workflow script to use latest stable rust toolchain

- ion-schema/src/isl/mod.rs
This PR adds an example of serializing ISL model into schema.
----
> adds an example of serializing ISL model into schema

- ion-schema/Cargo.toml
This PR bumps version to v0.9.0.
----
> Bumps version to v0.9.0

- ion-schema/Cargo.toml
This PR works on version bump to v0.9.1.
----
> Bumps version to v0.9.1(hotfix)

- ion-schema/Cargo.toml
- ion-schema/src/nfa.rs
- ion-schema/src/system.rs
This PR bumps version to `0.10.0`.
----
> Bumps version to 0.10.0

- ion-schema/Cargo.toml
This PR bumps the version to 0.11.0.
----
> Bumps version to v0.11.0

- ion-schema/Cargo.toml
None
Bump version so that we can release some of the latest improvements.
----
> Bumps version to v0.14.0

- ion-schema/Cargo.toml
Release the fix for `ordered_elements` (in #225).
----
> Bumps version to v0.14.1

- ion-schema-tests-runner/Cargo.toml
- ion-schema/Cargo.toml
- ion-schema/src/isl/mod.rs
- wasm-schema-sandbox/Cargo.toml
> Upgrades ion-rust dependency to v1.0.0-rc.10
